# theme: minima
remote_theme: jekyll/minima
plugins:
   - jekyll-remote-theme
minima:
  skin: auto
  hide_site_feed_link: true
title: "Soh Ee Zen 苏祎靖"
description: Mathematics is just art with a logical foundation
